apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  creationTimestamp: null
  labels:
    io.kompose.service: hazelcast
  name: hazelcast
spec:
  clusterIP: None
  ports:
  - name: hazelcast
    port: 5701
  selector:
    io.kompose.service: hazelcast
