apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/jplaroche_2017/kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: hazelcast
  name: hazelcast
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hazelcast
    spec:
      containers:
        image: gcr.io/superb-reporter-256719/hazelcast:latest
        name: hazelcast
        resources: {}
        volumeMounts:
        - mountPath: /tmp/coherence-archive
          name: coherence-share-claim
      restartPolicy: Always
      volumes:
      - name: coherence-share-claim
        persistentVolumeClaim:
          claimName: coherence-share-claim
status: {}
