apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/jplaroche_2017/kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: hazelcast
  name: hazelcast
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hazelcast
    spec:
      containers:
      - env:
        image: gcr.io/superb-reporter-256719/hazelcast:latest
        name: hazelcast
        resources: {}
        ports:
        - containerPort: 5071
          name: "hazelcast"
        volumeMounts:
        - mountPath: /tmp/hazelcast-archive
          name: hazelcast-share-claim
      restartPolicy: Always
      volumes:
      - name: hazelcast-share-claim
        persistentVolumeClaim:
          claimName: hazelcast-share-claim
status: {}
