apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: management-center
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: management-center
    spec:
      containers:
      - env:
        - name: MC_HTTP_PORT
          value: "8989"
        name: management-center
        image: hazelcast/management-center
