apiVersion: v1
kind: Service
metadata:
  name: management-center-internal
spec:
  clusterIP: None
  selector:
    app: management-center
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
status:
  loadBalancer: {}
