apiVersion: v1
kind: Service
metadata:
  name: management-center-public
spec:
  type: LoadBalancer
  selector:
    app: management-center
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
status:
  loadBalancer: {}