apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-configuration
data:
  hazelcast.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.10.xsd"
                   xmlns="http://www.hazelcast.com/schema/config"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <management-center enabled="true">http://management-center-internal:8989/hazelcast-mancenter</management-center>
      <properties>
            <property name="hazelcast.logging.type">log4j</property>
            <property name="log4j.configuration">log4j.properties</property>
      </properties>
      <network>
        <join>
          <multicast enabled="false"/>
          <kubernetes enabled="true" />
        </join>
      </network>
      <map name="Address">
      </map>
      <map name="AddressLink">
      </map>
      <map name="Customer">
      </map>
      <map name="Order">
      </map>
      <map name="OrderItem">
          <indexes>
             <index ordered="false">orderId</index>
          </indexes>
      </map>
    </hazelcast>

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast
  labels:
    app: hazelcast
  annotations:
    service-per-pod-label: "statefulset.kubernetes.io/pod-name"
    service-per-pod-ports: "5701:5701"
spec:
  replicas: 3
  serviceName: hazelcast-service
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      serviceAccountName: hazelcast-service-account
      containers:
      - name: hazelcast
        image: gcr.io/superb-reporter-256719/hazelcast:latest
        ports:
        - name: hazelcast
          containerPort: 5701
        volumeMounts:
        - name: hazelcast-storage
          mountPath: /data/hazelcast
        env:
        - name: JAVA_OPTS
          value: "-Dhazelcast.config=/data/hazelcast/hazelcast.xml"
      volumes:
      - name: hazelcast-storage
        configMap:
          name: hazelcast-configuration